### ISSUE TITLE
Feature: support https://ghcr.io (GitHub Container Registry) in addition to other supported container image registries

### ISSUE THREAD

**Issue by mskyttner** [KTH/aspen#13]
It seems Docker Hub and Azure Registry [are supported](https://github.com/KTH/aspen/blob/master/modules/util/environment.py#L18-L23).

Can [GitHub Container Registry](https://github.com/features/packages) also be used?

Currently images referenced like "ghcr.io/kth-library/shinyproxy-kth:${WEB_VERSION}" cannot be used, causing message "There are no images named shinyproxy-kth in the Docker registry, as specified in the docker-stack.yml. Misspelling or not pushed yet?".

**Comment by mictsi** [comment]
This project will be deprecated in the future. Our recommendation is to move away from the project.
