### ISSUE TITLE
Handle image path with extra path parameters 

### ISSUE THREAD

**Issue by jrolofsson** [KTH/aspen#6]
If docker-stack.yml defines the image path as: 
_image: registry.something.se/**something**/image-name:${PROJECT_VERSION}_ and not as:
_image: registry.something.se/image-name:${PROJECT_VERSION}_ the deployment fails with:
```
Error deploying **** in step *****-test.CalculateSemanticVersion
No matching version found for PROJECT_VERSION: 3.0.2_1c7e494  in the Docker registry. Not pushed yet?
```

**Comment by patricjansson** [comment]
Is that a limitation in Azure Container Registry maybe? We have images that use paths in the uri privateregistry.sys.kth.se**/se.kth.ite.cortina/**cms-api:latest
